### ISSUE TITLE
Preparing platform and designing the schematics on software and Simulating the project

### ISSUE THREAD

**Issue by mikeshams** [Surjeet-1995/capstone-project-summer-2020#2]

**Comment by mikeshams** [comment]
1. What will you do if you can not find a component in the library for Schematic Design?

**Comment by BINDU345** [comment]
If we don't find the exact components in EASYEDA library..so we would use the alternative that we have in library just to complete the schematic design.
For eg. In our project , Adafruit Wi Fi Module 802.11b/g/n we need. But we don't have in library. 
So we used usb_wifi_module for schematic design.
